baseurl = "https://www.jaiken.com"
title = "jaiken"
author = "Paul Wong"
copyright = "Copyright © 2024, Paul Wong"
canonifyurls = true
paginate = 3
theme = "silhouette-hugo"

pygmentsUseClasses = true

#disqusShortname = ""
#googleAnalytics = ""

[params]
author = ""
introDescription = "nothing to see, move along."
contentSharing = "All rights reserved."

[social]
#instagram = ""
#linkedin = ""
#twitter = ""
resume = "pwong.jaiken.com"
travel = "travel.jaiken.com"
email = "support@jaiken.com"
